name: Cyber News Bot

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:     # optional manual run

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the bot
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      run: |
        python cybernewsbot.py
